"""create user table

Revision ID: f370356ed716
Revises: 52c513e8b120
Create Date: 2025-10-16 15:53:36.899609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f370356ed716"
down_revision: Union[str, Sequence[str], None] = "52c513e8b120"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tasks_task_id_key"), "tasks", type_="unique")
    op.drop_column("tasks", "task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "task_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint(
        op.f("tasks_task_id_key"),
        "tasks",
        ["task_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
